In [1]:
import numpy as np
import pandas as pd

In [2]:
# Project Title: NYC - Yellow Taxi Demand, Revenue, and Efficiency Analysis
# Dataset Source: NYC Yellow Taxi and Limousines Data (NYC.Gov)
# Time Range : December 2024 - November 2025 (12 Months)

# Overview:
This notebook provides a comprehensive overview of the aggregated NYC Yellow Taxi datasets prepared from a raw trip-lebl dataset containing over 30 million records.

Due to large size of the raw cleaned data, analysis is conducted using aggregated dataframes (hourly_summary, daily_summary, monthly_summary, and borough_summary) to ensure efficient memory usage while preserving the analytical integrity of the data.

In [3]:
monthly_summary = pd.read_parquet('monthly_summary_ready.parquet')

In [4]:
monthly_summary

month  total_trips  total_revenue  revenue_per_trip  avg_distance  \
0   2024-12      3131288    90856299.57         29.015632      3.192428   
1   2025-01      2752626    74921291.61         27.218115      3.050282   
2   2025-02      2599121    69921520.90         26.901988      2.981682   
3   2025-03      3015063    84478047.48         28.018667      3.185436   
4   2025-04      2992143    84752728.14         28.325093      3.163116   
5   2025-05      3121083    92388448.11         29.601407      3.321262   
6   2025-06      2838991    83846836.23         29.534027      3.352754   
7   2025-07      2594458    75527143.65         29.110953      3.344164   
8   2025-08      2417131    71136705.10         29.430223      3.492977   
9   2025-09      2879717    86034769.29         29.876120      3.307509   
10  2025-10      3110938    92653556.54         29.783158      3.248464   
11  2025-11      2888381    84060611.67         29.103021      3.150982   

    avg_trip_duration_min  revenue_per_mile  revenue_per_min  avg_speed_mph  \
0               18.348315          9.088892         1.581379      10.439415   
1               14.577733          8.923149         1.867102      12.554551   
2               14.850492          9.022419         1.811522      12.046802   
3               15.649081          8.795866         1.790435      12.213251   
4               16.174112          8.954807         1.751261      11.733996   
5               17.439091          8.912698         1.697417      11.426957   
6               16.881824          8.808887         1.749457      11.916083   
7               16.379070          8.705001         1.777326      12.250382   
8               16.310868          8.425542         1.804332      12.849016   
9               17.617658          9.032817         1.695805      11.264296   
10              17.529622          9.168383         1.699019      11.118769   
11              17.052648          9.236175         1.706657      11.086777   

    pct_trips  pct_revenue  
0    9.118236     9.172049  
1    8.015581     7.563392  
2    7.568578     7.058659  
3    8.779792     8.528157  
4    8.713049     8.555887  
5    9.088519     9.326722  
6    8.267074     8.464436  
7    7.555000     7.624553  
8    7.038628     7.181333  
9    8.385667     8.685310  
10   9.058977     9.353485  
11   8.410897     8.486017

In [5]:
monthly_summary.shape

(12, 11)

In [6]:
# Total Rows : 12
# Total Columns : 11

In [7]:
hourly_summary = pd.read_parquet('hourly_summary_ready.parquet')

In [8]:
hourly_summary

hour  total_trips  avg_distance  avg_trip_duration_min  avg_speed_mph  \
0   12 AM       906085      3.953933              14.814035      16.014271   
1   01 AM       586182      3.462436              13.637324      15.233647   
2   02 AM       372693      3.039199              12.410103      14.693831   
3   03 AM       238342      3.200313              12.076259      15.900520   
4   04 AM       155964      4.524116              13.667195      19.861206   
5   05 AM       176703      5.640430              14.511529      23.321167   
6   06 AM       402413      4.346215              14.351367      18.170597   
7   07 AM       845335      3.419053              15.010847      13.666330   
8   08 AM      1196676      2.938067              15.114823      11.662990   
9   09 AM      1419864      2.869164              15.631537      11.012981   
10  10 AM      1587147      2.895709              16.220714      10.711154   
11  11 AM      1725125      2.887626              16.888705      10.258783   
12  12 PM      1879671      2.988708              17.305050      10.362435   
13  01 PM      1966247      3.115467              17.807063      10.497408   
14  02 PM      2116106      3.343237              19.146999      10.476537   
15  03 PM      2195138      3.294520              19.407841      10.185121   
16  04 PM      2248322      3.324869              19.405116      10.280390   
17  05 PM      2431282      3.044870              18.152928      10.064064   
18  06 PM      2504245      2.871408              16.375167      10.521081   
19  07 PM      2209780      3.072836              15.528217      11.873235   
20  08 PM      2026092      3.310463              15.183026      13.082228   
21  09 PM      2040298      3.350942              15.070185      13.341343   
22  10 PM      1796220      3.530120              15.448668      13.710385   
23  11 PM      1315013      3.905451              15.443512      15.173173   

    total_revenue  revenue_per_trip  revenue_per_mile  revenue_per_minute  
0     27206378.03         30.026298          7.594033            2.026882  
1     15967830.54         27.240397          7.867408            1.997489  
2      9347621.18         25.081290          8.252598            2.021038  
3      6162852.87         25.857184          8.079579            2.141158  
4      5149171.03         33.015125          7.297585            2.415647  
5      6702692.86         37.931970          6.725014            2.613920  
6     12285669.47         30.530001          7.024503            2.127324  
7     23063529.87         27.283302          7.979783            1.817572  
8     31345463.28         26.193776          8.915309            1.732986  
9     37661083.60         26.524430          9.244656            1.696854  
10    42899219.12         27.029140          9.334203            1.666335  
11    47273318.95         27.402837          9.489746            1.622554  
12    53394862.02         28.406493          9.504608            1.641515  
13    56269854.22         28.617897          9.185749            1.607109  
14    63546084.93         30.029727          8.982230            1.568378  
15    65060563.70         29.638485          8.996298            1.527140  
16    71052796.68         31.602589          9.504912            1.628570  
17    73316914.63         30.155661          9.903759            1.661201  
18    71590205.63         28.587541          9.955932            1.745786  
19    63433375.20         28.705742          9.341774            1.848618  
20    57417996.17         28.339284          8.560518            1.866511  
21    57991923.04         28.423261          8.482171            1.886059  
22    52410348.57         29.178134          8.265480            1.888715  
23    40028366.47         30.439521          7.794111            1.971023

In [9]:
hourly_summary.shape

(24, 9)

In [10]:
# Total Rows : 24
# Total Columns : 9

In [49]:
daily_summary = pd.read_parquet('daily_summary_ready.parquet')

In [50]:
daily_summary

date  total_trips  total_revenue  revenue_per_trip  avg_distance  \
0   2024-12-01        83203     2599639.59         31.244542      4.129789   
1   2024-12-02        98793     3113766.80         31.518091      3.819319   
2   2024-12-03       114301     3450449.95         30.187399      3.332373   
3   2024-12-04       117696     3543545.29         30.107610      3.188386   
4   2024-12-05       128789     3919818.75         30.435975      3.212644   
..         ...          ...            ...               ...           ...   
360 2025-11-26        84161     2401797.51         28.538129      2.948132   
361 2025-11-27        55420     1455818.81         26.268835      3.170484   
362 2025-11-28        71584     2031466.39         28.378777      3.165985   
363 2025-11-29        81290     2439054.06         30.004356      3.571083   
364 2025-11-30        75067     2372193.16         31.601012      4.012580   

     avg_trip_duration_min  revenue_per_mile  revenue_per_minute  \
0                17.503925          7.565651            1.785002   
1                19.112268          8.252280            1.649103   
2                18.832153          9.058829            1.602971   
3                19.301463          9.442899            1.559862   
4                20.051796          9.473808            1.517868   
..                     ...               ...                 ...   
360              17.117767          9.680073            1.667164   
361              13.677725          8.285435            1.920556   
362              15.204803          8.963649            1.866435   
363              16.907393          8.402032            1.774629   
364              16.642226          7.875484            1.898845   

     avg_speed_mph  pct_trips  pct_revenue  day_of_week  day_of_year  
0        14.156101   0.242335     0.262441            6          336  
1        11.990159   0.287743     0.314344            0          337  
2        10.617076   0.332911     0.348333            1          338  
3         9.911330   0.342799     0.357731            2          339  
4         9.613036   0.375108     0.395717            3          340  
..             ...        ...          ...          ...          ...  
360      10.333584   0.245126     0.242468            2          330  
361      13.907942   0.161415     0.146969            3          331  
362      12.493360   0.208494     0.205082            4          332  
363      12.672857   0.236764     0.246229            5          333  
364      14.466504   0.218639     0.239480            6          334  

[365 rows x 13 columns]

In [51]:
daily_summary.shape

(365, 13)

In [52]:
# Total Rows: 365 (Representing 334 days of the year -> (11 months))
# Total Columns: 13

In [15]:
borough_summary = pd.read_parquet('borough_summary_ready.parquet')

In [16]:
borough_summary

borough                     zone  total_trips  total_revenue  \
0              EWR           Newark Airport         1150      112811.78   
1           Queens              Jamaica Bay           58        4084.37   
2            Bronx  Allerton/Pelham Gardens           83        2620.61   
3        Manhattan            Alphabet City        41564     1014629.74   
4    Staten Island            Arden Heights            3         180.68   
..             ...                      ...          ...            ...   
255          Bronx       Woodlawn/Wakefield           97        3851.04   
256         Queens                 Woodside         6919      335871.24   
257      Manhattan       World Trade Center       175243     5789869.46   
258      Manhattan           Yorkville East       443050     9815077.73   
259      Manhattan           Yorkville West       634574    13291839.21   

     avg_distance  avg_trip_duration_min  avg_speed_mph  revenue_per_trip  \
0        3.322617               8.346101      23.886247         98.097200   
1       15.051379              39.061207      23.119684         70.420172   
2        5.029398              17.543373      17.201016         31.573614   
3        2.570325              14.114873      10.926026         24.411263   
4        4.563333              19.766667      13.851602         60.226667   
..            ...                    ...            ...               ...   
255      6.193814              19.582302      18.977792         39.701443   
256      4.434326              18.007665      14.774794         48.543321   
257      4.062693              20.585504      11.841418         33.039091   
258      2.274574              12.142443      11.239455         22.153431   
259      2.056588              11.453183      10.773886         20.946082   

     revenue_per_mile  revenue_per_min  
0           29.524073        11.753655  
1            4.678652         1.802816  
2            6.277812         1.799746  
3            9.497347         1.729471  
4           13.197955         3.046880  
..                ...              ...  
255          6.409854         2.027414  
256         10.947171         2.695703  
257          8.132314         1.604969  
258          9.739596         1.824463  
259         10.184870         1.828844  

[260 rows x 10 columns]

In [17]:
borough_summary.shape

(260, 10)

In [18]:
# Total Rows: 260 (Representating Total 260 zones in NY within 5 boroughs)
# Total Columns: 10

In [19]:
monthly_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype    
---  ------                 --------------  -----    
 0   month                  12 non-null     period[M]
 1   total_trips            12 non-null     int64    
 2   total_revenue          12 non-null     float64  
 3   revenue_per_trip       12 non-null     float64  
 4   avg_distance           12 non-null     float64  
 5   avg_trip_duration_min  12 non-null     float64  
 6   revenue_per_mile       12 non-null     float64  
 7   revenue_per_min        12 non-null     float64  
 8   avg_speed_mph          12 non-null     float64  
 9   pct_trips              12 non-null     float64  
 10  pct_revenue            12 non-null     float64  
dtypes: float64(9), int64(1), period[M](1)
memory usage: 1.2 KB


In [20]:
monthly_summary.head()

month  total_trips  total_revenue  revenue_per_trip  avg_distance  \
0  2024-12      3131288    90856299.57         29.015632      3.192428   
1  2025-01      2752626    74921291.61         27.218115      3.050282   
2  2025-02      2599121    69921520.90         26.901988      2.981682   
3  2025-03      3015063    84478047.48         28.018667      3.185436   
4  2025-04      2992143    84752728.14         28.325093      3.163116   

   avg_trip_duration_min  revenue_per_mile  revenue_per_min  avg_speed_mph  \
0              18.348315          9.088892         1.581379      10.439415   
1              14.577733          8.923149         1.867102      12.554551   
2              14.850492          9.022419         1.811522      12.046802   
3              15.649081          8.795866         1.790435      12.213251   
4              16.174112          8.954807         1.751261      11.733996   

   pct_trips  pct_revenue  
0   9.118236     9.172049  
1   8.015581     7.563392  
2   7.568578     7.058659  
3   8.779792     8.528157  
4   8.713049     8.555887

In [21]:
hourly_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   hour                   24 non-null     object 
 1   total_trips            24 non-null     int64  
 2   avg_distance           24 non-null     float64
 3   avg_trip_duration_min  24 non-null     float64
 4   avg_speed_mph          24 non-null     float64
 5   total_revenue          24 non-null     float64
 6   revenue_per_trip       24 non-null     float64
 7   revenue_per_mile       24 non-null     float64
 8   revenue_per_minute     24 non-null     float64
dtypes: float64(7), int64(1), object(1)
memory usage: 1.8+ KB


In [22]:
borough_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   borough                260 non-null    object 
 1   zone                   260 non-null    object 
 2   total_trips            260 non-null    int64  
 3   total_revenue          260 non-null    float64
 4   avg_distance           260 non-null    float64
 5   avg_trip_duration_min  260 non-null    float64
 6   avg_speed_mph          260 non-null    float64
 7   revenue_per_trip       260 non-null    float64
 8   revenue_per_mile       260 non-null    float64
 9   revenue_per_min        260 non-null    float64
dtypes: float64(7), int64(1), object(2)
memory usage: 20.4+ KB


In [23]:
daily_summary.shape

(334, 13)

# Daily_Summary Documentation:
"""
The daily summary aggregates NYC Yellow Taxi trips by calendar date.
The dataset spans **December 2024 through November 2025**. 
After aggregation, the summary contains **365 unique days**, reflecting every day with recorded trips.
This ensures full alignment with the raw dataset and consistency with monthly summary periods.
All daily metrics are based on actual trips, preserving the integrity of the data for temporal analysis.
"""


# Monthly_Summary Documentation:
In the monthly summary, trips were grouped by calendar month. The dataset spans from December 2024 through November 2025, resulting in 12 monthly aggregation periods. Each row represents one complete calendar month with available trip data.

The monthly summary reflects the true temporal coverage of the dataset and is used to analyze long-term demand trends, revenue distribution, and seasonal efficiency patterns across the year.


# Hourly_Summary Documentation:
In the hourly summary, trips were aggregated by hour of day (0–23) across the entire dataset. This aggregation produces exactly 24 rows, corresponding to each hour in a 24-hour day.

The hourly summary enables identification of peak and off-peak demand periods, revenue efficiency by hour, and operational performance trends without being affected by missing calendar dates.


# Borough_Summary Documentation:
In the borough (zone-level) summary, trips were grouped by pickup location zones present in the dataset. The summary contains 260 rows, representing active taxi zones with valid trip records after data cleaning.

Some TLC zones are excluded due to invalid location identifiers or insufficient data coverage. The resulting summary accurately reflects the geographic distribution of taxi demand, revenue, and efficiency across operational areas.


# Dataset Loading and Shape Validation

In [24]:
monthly_summary.shape

(12, 11)

In [53]:
daily_summary.shape

(365, 13)

In [54]:
hourly_summary.shape

(24, 9)

In [55]:
borough_summary.shape

(260, 10)

# Shape and Aggregation Documentation

## Monthly_Summary:
### The monthly_summary dataset represents month-level aggregation of NYC Yellow Taxi trips across the full analysis period
### Rows: 12
### Columns: 11
### Each row corresponds to a calendar month between December 2024 and November 2025, 
### containing aggregated demand, revenue, and efficiency metrics.
### This dataset supports long-term trend analysis and month-over-month comparison.




## Daily_Summary:
### The daily_summary dataset aggregates taxi trips at the daily level across the defined time range.
### Rows: 365
### Columns: 13
### Each row represents one day of taxi operations, enabling weekday vs weekend comparisons
### and short-term demand variability analysis.





## Hourly_Summary:
### The hourly_summary dataset captures hour-of-day aggregation across the entire dataset.
### Rows: 24
### Columns: 9
### each row corresponds to an hour allowing identification of:
### 1. peak demand hours
### 2. revenue and efficiency patterns by time of day



## Borough_Summary:
### The borough_summary dataset provides geographic aggregation of NYC Yellow Taxi activity.
### Rows: 260
### Columns: 10
### each row represens an active taxi pickup zone included in the analysis.
### zones excluded during data cleaning (invalid or low-activiy zones) account for fewer rows than the full TLC Zone count.
### This dataset enables spatial comparison of demand, revenue, and efficiency.